// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5dysmsrQ02fc5zU2lQZunPvcit9L56Y',
    appId: '1:298677662014:web:12a9d7b6efcb8cc2d7bc6f',
    messagingSenderId: '298677662014',
    projectId: 'chat-28883',
    authDomain: 'chat-28883.firebaseapp.com',
    storageBucket: 'chat-28883.firebasestorage.app',
    measurementId: 'G-L05Z9S9YDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFWzl9rJ2_SOD1ptxiTC_UMpJHki7z8A',
    appId: '1:298677662014:android:4ee678a70dd865a7d7bc6f',
    messagingSenderId: '298677662014',
    projectId: 'chat-28883',
    storageBucket: 'chat-28883.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5xqpzkeke71obn4rqi1C0uxKYfDYkCA',
    appId: '1:298677662014:ios:4c5af4253bd6cf64d7bc6f',
    messagingSenderId: '298677662014',
    projectId: 'chat-28883',
    storageBucket: 'chat-28883.firebasestorage.app',
    iosBundleId: 'com.example.appProect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5xqpzkeke71obn4rqi1C0uxKYfDYkCA',
    appId: '1:298677662014:ios:4c5af4253bd6cf64d7bc6f',
    messagingSenderId: '298677662014',
    projectId: 'chat-28883',
    storageBucket: 'chat-28883.firebasestorage.app',
    iosBundleId: 'com.example.appProect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ5dysmsrQ02fc5zU2lQZunPvcit9L56Y',
    appId: '1:298677662014:web:a2ee957c81569dfed7bc6f',
    messagingSenderId: '298677662014',
    projectId: 'chat-28883',
    authDomain: 'chat-28883.firebaseapp.com',
    storageBucket: 'chat-28883.firebasestorage.app',
    measurementId: 'G-B2DS2RXJKH',
  );

}